[project]
name = "stanet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.5.1",
    "torchvision>=0.1.6",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu121"
default = true
